sql
CREATE TABLE Categories (
Id UUID PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Description TEXT,
Color VARCHAR(7) DEFAULT '#007bff',
UserId UUID NOT NULL,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);