sql
CREATE TABLE TaskAttachments (
Id UUID PRIMARY KEY,
TaskId UUID NOT NULL,
FileName VARCHAR(255) NOT NULL,
FilePath VARCHAR(500) NOT NULL,
FileSize BIGINT NOT NULL,
ContentType VARCHAR(100) NOT NULL,
UploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE
);