sql
CREATE TABLE TaskComments (
Id UUID PRIMARY KEY,
TaskId UUID NOT NULL,
UserId UUID NOT NULL,
Comment TEXT NOT NULL,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE,
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);