sql
CREATE TABLE Tasks (
Id UUID PRIMARY KEY,
Title VARCHAR(200) NOT NULL,
Description TEXT,
Priority INTEGER DEFAULT 1 CHECK (Priority BETWEEN 1 AND 5),
Status INTEGER DEFAULT 0,
DueDate TIMESTAMP,
CompletedAt TIMESTAMP,
UserId UUID NOT NULL,
CategoryId UUID,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE SET NULL
);